//DefaultUserInfo
username=testuser1
password=laundry365!

//UserInfoForUpdate
wrongpwd=wrongpassword
testpwd=testpwd123!
mismatchpwd=mismatch123!
profileImagePath=src/main/resources/testimage/profile.jpg
profileImageBackupPath=src/main/resources/testimage/beforeprofile.jpg

//URLs
url=http://laundry365.store:8080/
MyinfoupdatePageURL=http://laundry365.store:8080/LoginInfo/Mypage/MyInfoUpdateForm
ChangePasswordPageURL=http://laundry365.store:8080/LoginInfo/Mypage/MyInfoUpdateFormPwd
MyInfoDeleteURL=http://laundry365.store:8080/LoginInfo/Mypage/null/LoginInfo/Mypage/MyInfoDelete
ComintroPageURL=http://laundry365.store:8080/Corporation/Brand
HistoryPageURL=http://laundry365.store:8080/Corporation/History
StartupPageURL=http://laundry365.store:8080/Corporation/Startup