//DefaultUserInfo
username=testuser1
password=laundry365!
useremail=nheoik93@gmail.com

//anotherUserInfo
anotherusername=testuser2
anotheruserpassword=laundry365@

//AdminUSerImnfo
adminusername=admintestuser1
adminpassword=laundry365!
adminemail=admin@test.com

adminusername2=kim9502071
adminpassword2=1q2w3e4r12!

//UserInfoForUpdate
wrongpwd=wrongpassword
testpwd=testpwd123!
mismatchpwd=mismatch123!
profileImagePath=src/main/resources/testimage/profile.jpg
profileImageBackupPath=src/main/resources/testimage/beforeprofile.jpg

//TestDataUserAddress
NewTestAddress.postcode=06159
NewTestAddress.mainAddr=TestCity MainAddress
NewTestAddress.detailAddr=TestStreet DetailAddress
NewTestAddress.extraAddr=TestExtraAddress

//URLs
url=http://laundry365.store:8080/
MyinfoupdatePageURL=http://laundry365.store:8080/LoginInfo/Mypage/MyInfoUpdateForm
ChangePasswordPageURL=http://laundry365.store:8080/LoginInfo/Mypage/MyInfoUpdateFormPwd
MyInfoPageURL=http://laundry365.store:8080/LoginInfo/Mypage/MyInfo

UseHistoryPageURL=http://laundry365.store:8080/LoginInfo/Mypage/OrderList
UseHistoryNaviPageURl=http://laundry365.store:8080/LoginInfo/Mypage/OrderList?pageNum=
ReviewDetailPageURL=http://laundry365.store:8080/Review/ReviewDetail?code=

ComintroPageURL=http://laundry365.store:8080/Corporation/Brand
HistoryPageURL=http://laundry365.store:8080/Corporation/History
StartupPageURL=http://laundry365.store:8080/Corporation/Startup
AreaGuidePageURL=http://laundry365.store:8080/Guide/AreaGuide
PriceGuidePAgeURL=http://laundry365.store:8080/Guide/PriceGuide
BookinginfoPageURL=http://laundry365.store:8080/Reserve/ReserveSelect
BookingClothesURL=http://laundry365.store:8080/Reserve/Select?category=clothes
BookingBeddingURL=http://laundry365.store:8080/Reserve/Select?category=bedding
BookingShoesRUL=http://laundry365.store:8080/Reserve/Select?category=shoes
BookingLivingURL=http://laundry365.store:8080/Reserve/Select?category=living
BookingPaymentURL=http://laundry365.store:8080/Reserve/Payment
OrderDetailPageURL=http://laundry365.store:8080/LoginInfo/Mypage/OrderDetail?code=
ReviewCreatePageURL=http://laundry365.store:8080/Review/ReviewDetail?code=

ReviewBoardPageURL=http://laundry365.store:8080/Review/List
FAQBoardPageURL=http://laundry365.store:8080/Faq/List
FAQCreatePageURL=http://laundry365.store:8080/Faq/FaqInsertForm
FQAModifyPageURL=http://laundry365.store:8080/Faq/FaqUpdateForm?num=
QnABoardPageURL=http://laundry365.store:8080/Qna/List
QnADetailPageURL=http://laundry365.store:8080/Qna/QnaDetail?num=
QnACreatePageURL=http://laundry365.store:8080/Qna/QnaInsertForm
NoticePageURL=http://laundry365.store:8080/Notice/List
NoticeDetailPageURL=http://laundry365.store:8080/Notice/NoticeDetail?num=
NoticeCreatePageURL=http://laundry365.store:8080/Notice/NoticeInsertForm
NoticeModifyPageURL=http://laundry365.store:8080/Notice/NoticeUpdateForm?num=

DeliveryTrackerURL = https://tracker.delivery/



//Report_Email_Settings
email.user=nheoik93@gmail.com
email.password=yfkd ecia cutu dluv
email.to=nheoik93@gmail.com

//WebDriver_Settings
headless=true

//Areaguide_src
areaIMG=http://laundry365.store:8080/images/areaImg.png

//PriceGuideData
PriceGuideDataPath=src/main/resources/config/PriceGuideData.xlsx

//BookinginfoPage_src
clothes_Img_src=http://laundry365.store:8080/images/service1.png
bedding_Img_src=http://laundry365.store:8080/images/service2.png
shoes_Img_src=http://laundry365.store:8080/images/service3.png
living_Img_src=http://laundry365.store:8080/images/service4.png

//BookingCategoryPage_src
Category_clothes_Img_src=http://laundry365.store:8080/images/990A4A4A5DB90F5C2F.png
Category_bedding_Img_src=http://laundry365.store:8080/images/10_1555258129.png
Category_shoes_Img_src=http://laundry365.store:8080/images/%EC%9A%B4%EB%8F%99%ED%99%94%EB%B9%A8%EB%9E%98%EB%B0%A9%EB%B2%95.jpg
Category_living_Img_src=http://laundry365.store:8080/images/Z4C60MKTH4DOG0TBN5AL.jpg

explainImg_1=http://laundry365.store:8080/images/umile_vx_1-768x303.png
explainImg_2=http://laundry365.store:8080/images/%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C.jpg
explainImg_3=http://laundry365.store:8080/images/96167986-%ED%8F%89%EB%A9%B4-%ED%98%84%EB%8C%80%EC%A0%81%EC%9D%B8-%EB%94%94%EC%9E%90%EC%9D%B8%EC%97%90-%EC%84%B8%ED%83%81-%EC%84%9C%EB%B9%84%EC%8A%A4-%EB%B2%A1%ED%84%B0-%EC%9D%BC%EB%9F%AC%EC%8A%A4%ED%8A%B8%EC%9E%85%EB%8B%88%EB%8B%A4-%EC%B2%AD%EC%86%8C-%EA%B0%9C%EB%85%90.webp
explainImg_4=http://laundry365.store:8080/images/115710901-%EC%84%B8%ED%83%81-%EB%B0%8F-%EA%B9%A8%EB%81%97%ED%95%9C-%EC%95%84%EC%9D%B4%EC%BD%98%EC%9D%98-%EA%B3%A0%EB%A6%BD-%EB%90%9C-%EA%B0%9C%EC%B2%B4%EC%9E%85%EB%8B%88%EB%8B%A4-%EC%A3%BC%EC%8B%9D%EC%97%90-%EB%8C%80-%ED%95%9C-%EC%84%B8%ED%83%81-%EB%B0%8F-%EC%98%B7-%EB%B2%A1%ED%84%B0-%EC%95%84%EC%9D%B4%EC%BD%98%EC%9D%98-%EC%A7%91%ED%95%A9%EC%9E%85%EB%8B%88%EB%8B%A4-.webp

//ReviewDetailPage_src
ReviewDetailPage_Img_src=http://laundry365.store:8080/images/laundry3.png



//TestDummyData
FQA_Title = Test Dummy FQA Title
FQA_Content = Test Dummy FQA Content
FQA_Title_Modify = Test Dummy FQA Modify Title 123
FQA_Content_Modify = Test Dummy FQA Modify Content 123
OderDetail_Test_OderNum_1 = "3"

Notice_Title = Test Dummy Notice Title
Notice_Content = Test Dummy Notice Content
Notice_Title_Modify = Test Dummy Notice Modify Title 123
Notice_Content_Modify = Test Dummy Notice Modify Content 123

QnA_Title = Test Dummy QnA Title
QnA_Content = Test Dummy QnA Content
QnA_AdminAnswer = Test Dummy QnA Admin Answer
QnA_AdminAnswer_Modify = Test Dummy QnA Admin Answer Modify 123


